# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 790241763e6de1d0c3fb7f4ee11b639051aa927b9054faebc0b7577696f9bf750a052945ffa1be49a2e5710666854d29dc969fa0caed5133bad95dfde2ea5942

test:
  secret_key_base: 49b4bac0837178d6d399e16ff3cc4edc81902082978ba09ed0e3e8e4e0a2af3cae338f1de192bc8ada432c84d850b1203d07700aac27aa816ab02a9eda0be715

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
